title: Hola, mundo! Soy José Luis Molero
description: > # this means to ignore newlines until "baseurl:"
  Esta es sólo una muestras de mis trabajos como editor y copywriter en castellano,
  así como traductor inglés-español
permalink: ':title/'
baseurl: "/betaBlog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: José Luis Molero # add your name
author-img: jlmolero.jpg # add your photo
about-author: Escritor y traductor de textos especializado en tecnología, energías alternativas, TV y
  deportes. # add description
twitter: jlmolero # add your Twitter handle
facebook: # add your Facebook handle
github: jlmolero # add your Github handle
linkedin: # add your Linkedin handle
email: jlmolero@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
